apiVersion: argoproj.io/v1alpha1 
kind: Application 
metadata: 
  name: mmounib
  namespace: argocd 
spec: 
  project: default
  source: 
    repoURL: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/k8s-bonus.git
    targetRevision: HEAD 
    path: ./
  destination: 
    server: https://kubernetes.default.svc 
    namespace: devbonus 
  syncPolicy: 
    automated: 
      prune: true 
      selfHeal: true