apiVersion: argoproj.io/v1alpha1 
kind: Application 
metadata: 
  name: araysse
  namespace: argocd 
spec: 
  project: default
  source: 
    repoURL: https://github.com/mmounib/k8s-p3.git
    targetRevision: HEAD 
    path: ./
  destination: 
    server: https://kubernetes.default.svc 
    namespace: dev 
  syncPolicy: 
    automated: 
      prune: true 
      selfHeal: true
