Vagrant.configure("2") do |config|
  config.vm.box = "boxomatic/alpine-3.20"

  # Define the Kubernetes controller node
  config.vm.define "araysseS" do |controller|
    controller.vm.hostname = "serverS"
    controller.vm.network "private_network", ip: "192.168.56.110"

    controller.vm.provider "virtualbox" do |vb|
    vb.memory = 2048 
      vb.cpus = 1 
    end

    controller.vm.provision "shell", path: "./scripts/server.sh"
  end
end
