Vagrant.configure("2") do |config|
  # Base box configuration

  # Define the Kubernetes controller node
  config.vm.define "araysseS" do |controller|
    controller.vm.box = "boxomatic/alpine-3.20"
    controller.vm.hostname = "araysseS"
    controller.vm.network "private_network", ip: "192.168.56.110"
    controller.vm.synced_folder "./confs", "/vagrant_data", type: "virtualbox"
    controller.vm.provider "virtualbox" do |vb|
      vb.memory = 1024 
      vb.cpus = 1 
    end

    # Provision the controller: install K3s and kubectl
    controller.vm.provision "shell", path: "./scripts/server.sh"
  end

  # Define the Kubernetes worker node
  config.vm.define "araysseSW" do |worker|
    worker.vm.box = "boxomatic/alpine-3.20"
    worker.vm.hostname = "araysseSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    worker.vm.synced_folder "./confs", "/vagrant_data", type: "virtualbox"

    # Provision the worker: install K3s in agent mode and join it to the controller
    worker.vm.provision "shell", path: "./scripts/worker.sh"
  end
end
